/*************faq insert*******************/
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문1','자주찾는질문내용1','카테고리1');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문2','자주찾는질문내용2','카테고리1');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문3','자주찾는질문내용3','카테고리1');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문4','자주찾는질문내용4','카테고리2');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문5','자주찾는질문내용5','카테고리2');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문6','자주찾는질문내용6','카테고리2');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문7','자주찾는질문내용7','카테고리3');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문8','자주찾는질문내용8','카테고리3');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문9','자주찾는질문내용9','카테고리3');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문10','자주찾는질문내용10','카테고리4');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문11','자주찾는질문내용11','카테고리4');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문12','자주찾는질문내용12','카테고리4');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문13','자주찾는질문내용13','카테고리5');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문14','자주찾는질문내용14','카테고리5');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문15','자주찾는질문내용15','카테고리5');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문16','자주찾는질문내용16','카테고리6');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문17','자주찾는질문내용17','카테고리6');
insert into faq values(FAQ_FAQ_NO_SEQ.nextval,'자주찾는질문18','자주찾는질문내용18','카테고리6');
